# Generated by Django 5.2.8 on 2026-07-13 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
