# Generated by Django 5.2.8 on 2026-07-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=122),
        ),
    ]
